# Generated by Django 3.2.8 on 2021-10-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AddField(
            model_name='product',
            name='audio',
            field=models.FileField(blank=True, upload_to='Dictionary/media'),
        ),
    ]
